### ISSUE TITLE
require win 10 exe file 

### ISSUE THREAD

**Issue by warthog911** [mempool/mempool-cli#12]
Can it be made for win 10. Want to link with my bitcoin core software. Like linking electrum with bwt plugin

**Comment by qustavo** [comment]
did you try the windows release?

**Comment by warthog911** [comment]
!!!
Where is it. please direct me to the link.
Regards,
Anand

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by qustavo** [comment]
https://github.com/mempool/mempool-cli/releases/tag/v2.0.3 
The link should be in the README.md

**Comment by warthog911** [comment]
Apologies but i cant seem to find any win 10 exe file. Opening the readme.md give me this

# mempool-cli

[mempool.space](https://mempool.space/) for the terminal
![mempool screenshot](https://github.com/gchaincl/mempool/raw/master/share/screenshot.png)

Mempool is a mempool visualizer for the Bitcoin blockchain inspired by
[mempool.space](https://mempool.space/). It connects to the same API endpoint but the block rendering happens on your terminal.

:warning: This software is being under developement, things might break :warning:
# Install
Get a pre-built [release](https://github.com/gchaincl/mempool/releases/latest)

### development version
```bash
go get -u github.com/mempool/mempool-cli
```

### Docker
```bash
docker run -it mempool/mempool-cli
```

# Usage
### Key bindings
Key | Description
------------------|--------------------------------------
Ctrl+c | Quit
f | Opens Tx search
click | Opens info for a selected block

# TODO
- [x] Transaction Tracking (by Tx ID) (using 'f' key)
- [x] Block details on click
- [ ] Graphs
- [ ] Tx weight per second progress bar- [ ] Custom API endpoint

I actually want to link bitcoin core with a mempool app for win 10. I have yet to find any technique which allows me to view the blockchain data\tx address via my closed environment using bitcoin core app. I have been able to link electrum with bitcoin core via bwt plugin as watch only mode and use my pi 400 as cold storage and signing tx.

Other packages like umbrel and mynode require entire blockchain to be downlaoded in a seperate harddisk and work in an linux enviroment

I hope you can solve this problem one day by creating a mempool visual viewer querying bitcoin core which is installed in the hard disk. If bitcoin has to be adopted by masses it has to be simple to use. linux commands go over the head of most average people. It took me hours and hours just to install electrum in arm x86 64 processor and create a desktop icon in raspberry pi 400 (ubuntu 22.04)

ps: you could make a youtube video guide on how to install mempool. It would help us alot.

this was my query on bitcoin forum
https://bitcointalk.org/index.php?topic=5395810.0

Regards,
Anand
Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by qustavo** [comment]
read the readme, there you can find the link to the releases page.
